version: '3'

services:

    git:
        image: alpine/git
        volumes:
            - "codebase:/git"
        command:
            - clone
            - ${PROJECT_REPOSITORY}
            - .

    composer:
        image: composer
        volumes:
            - "codebase:/app"
        command:
            - toolkit-install

    web:
        image: fpfis/php71-dev
        volumes:
            - "codebase:/var/www/html"
            - "/tmp:/cache"
        depends_on:
            - mysql
        ports:
            - "8080"
        command: "/bin/bash -c './toolkit/phing build-platform build-subsite-dev install-clean'"

    mysql:
        image: fpfis/mysql56

volumes:
    codebase:
