version: '3'

services:

    web:
        image: fpfis/php71-dev
        environment:
            - CACHE_PREFIX=/tmp/drush
        volumes:
            - "codebase:/var/www/html"
            - "/home/verbral/portainer-compose/templates/stacks/subsite-${BUILD_TYPE:-clone}.sh:/build.sh"
            - "/tmp:/cache"
        depends_on:
            - mysql
        ports:
            - "8080"
        command: "/bin/bash -c '/build.sh'"

    mysql:
        image: fpfis/mysql56

#    dkrc:
#        image: docker/compose:1.18.0
#        privileged: true
#        restart: "no"
#        working_dir: $PWD
#        volumes:
#            - "./subsite.yml:$PWD/docker-compose.yml"
#            - "/var/run/docker.sock:/var/run/docker.sock"
#        command: "exec -T --user web web /bin/bash -c /build.sh"
#        depends_on:
#            - web

